// Mission data derived from "Cooking for Strangers to Save the World" (Vlad Briantsev & Orly Israel).

const CITIES = {
  ny:  { name: "New York",    short: "NYC", part: "Part One",   tagline: "No crew, no plan, a knife roll and a lot of nerve.", color: "#8b6f5c", roof: "#5e4a3d", accent: "#f2c14e", police: "NYPD",     quadrant: [0, 0] },
  fl:  { name: "Florida",     short: "FLA", part: "Part Two",   tagline: "Cold approaches and Shabbat tables.",                color: "#e8b4a2", roof: "#c4867a", accent: "#7fd3c9", police: "Miami PD", quadrant: [1, 0] },
  chi: { name: "Chicago",     short: "CHI", part: "Part Three", tagline: "The one I'd been walking toward.",                    color: "#7a3b3b", roof: "#4f2626", accent: "#cbd5e1", police: "CPD",      quadrant: [0, 1] },
  la:  { name: "Los Angeles", short: "LA",  part: "Part Four",  tagline: "Rice first. Always.",                                 color: "#d9c39a", roof: "#a89066", accent: "#fb923c", police: "LAPD",     quadrant: [1, 1] },
};
const CITY_ORDER = ["ny", "fl", "chi", "la"];

const SHOPS = {
  produce: { name: "Produce Market", icon: "🥬", color: "#65a30d" },
  meat:    { name: "Butcher & Fish", icon: "🐟", color: "#dc2626" },
  pantry:  { name: "Grocery",        icon: "🛒", color: "#2563eb" },
};

const ING = {
  tomato:      { name: "Tomatoes",           shop: "produce", price: 4 },
  cucumber:    { name: "Cucumbers",          shop: "produce", price: 3 },
  onion:       { name: "Onions",             shop: "produce", price: 2 },
  garlic:      { name: "Garlic",             shop: "produce", price: 2 },
  lemon:       { name: "Lemons",             shop: "produce", price: 3 },
  lime:        { name: "Limes",              shop: "produce", price: 3 },
  herbs:       { name: "Fresh Herbs",        shop: "produce", price: 4 },
  avocado:     { name: "Avocados",           shop: "produce", price: 6 },
  broccoli:    { name: "Broccoli",           shop: "produce", price: 4 },
  sweetpotato: { name: "Sweet Potato",       shop: "produce", price: 3 },
  asparagus:   { name: "Asparagus",          shop: "produce", price: 7 },
  potato:      { name: "Potatoes",           shop: "produce", price: 3 },
  brussels:    { name: "Brussels Sprouts",   shop: "produce", price: 5 },
  lettuce:     { name: "Baby Gem Lettuce",   shop: "produce", price: 4 },
  cabbage:     { name: "Red Cabbage",        shop: "produce", price: 3 },
  mushroom:    { name: "Maitake Mushrooms",  shop: "produce", price: 8 },
  scallion:    { name: "Green Onions",       shop: "produce", price: 2 },
  chili:       { name: "Chilies",            shop: "produce", price: 3 },
  eggplant:    { name: "Eggplant",           shop: "produce", price: 4 },
  cauliflower: { name: "Cauliflower",        shop: "produce", price: 4 },
  spinach:     { name: "Spinach",            shop: "produce", price: 4 },
  banana:      { name: "Bananas",            shop: "produce", price: 3 },
  strawberry:  { name: "Strawberries",       shop: "produce", price: 6 },
  orange:      { name: "Oranges",            shop: "produce", price: 3 },
  cherry:      { name: "Cherries",           shop: "produce", price: 7 },
  snappeas:    { name: "Snap Peas",          shop: "produce", price: 5 },
  carrot:      { name: "Heirloom Carrots",   shop: "produce", price: 4 },
  apple:       { name: "Apples",             shop: "produce", price: 3 },
  bokchoy:     { name: "Bok Choy",           shop: "produce", price: 4 },
  lemongrass:  { name: "Lemongrass",         shop: "produce", price: 4 },
  tomatillo:   { name: "Tomatillos",         shop: "produce", price: 5 },
  chicken:     { name: "Chicken Thighs",     shop: "meat", price: 9 },
  wholechicken:{ name: "Whole Chicken",      shop: "meat", price: 12 },
  turkey:      { name: "Turkey Legs",        shop: "meat", price: 11 },
  ribeye:      { name: "Ribeye",             shop: "meat", price: 22 },
  filet:       { name: "Filet Mignon",       shop: "meat", price: 26 },
  skirt:       { name: "Skirt Steak",        shop: "meat", price: 16 },
  strip:       { name: "New York Strip",     shop: "meat", price: 21 },
  brisket:     { name: "Brisket",            shop: "meat", price: 30 },
  veal:        { name: "Veal Cutlets",       shop: "meat", price: 20 },
  groundbeef:  { name: "Ground Beef",        shop: "meat", price: 10 },
  shortrib:    { name: "Short Ribs",         shop: "meat", price: 24 },
  salmon:      { name: "Salmon",             shop: "meat", price: 14 },
  tuna:        { name: "Tuna",               shop: "meat", price: 18 },
  hamachi:     { name: "Hamachi",            shop: "meat", price: 19 },
  halibut:     { name: "Halibut",            shop: "meat", price: 18 },
  mahi:        { name: "Mahi Mahi",          shop: "meat", price: 14 },
  shrimp:      { name: "Shrimp",             shop: "meat", price: 13 },
  scallop:     { name: "Scallops",           shop: "meat", price: 17 },
  crab:        { name: "Crab",               shop: "meat", price: 15 },
  oysters:     { name: "Oysters",            shop: "meat", price: 16 },
  roe:         { name: "Trout Roe",          shop: "meat", price: 15 },
  unagi:       { name: "Unagi",              shop: "meat", price: 17 },
  uni:         { name: "Uni",                shop: "meat", price: 28 },
  wagyu:       { name: "Wagyu",              shop: "meat", price: 45 },
  bacon:       { name: "Bacon",              shop: "meat", price: 8 },
  pork:        { name: "Pork Belly",         shop: "meat", price: 10 },
  iberico:     { name: "Iberico Ham",        shop: "meat", price: 24 },
  chickpeas:   { name: "Dried Chickpeas",    shop: "pantry", price: 3 },
  tahini:      { name: "Tahini",             shop: "pantry", price: 6 },
  pita:        { name: "Pita & Laffa",       shop: "pantry", price: 4 },
  matzo:       { name: "Matzo",              shop: "pantry", price: 4 },
  rice:        { name: "Jasmine Rice",       shop: "pantry", price: 4 },
  sushirice:   { name: "Sushi Rice",         shop: "pantry", price: 6 },
  nori:        { name: "Nori",               shop: "pantry", price: 5 },
  soy:         { name: "Soy, Mirin & Sake",  shop: "pantry", price: 7 },
  flour:       { name: "Flour",              shop: "pantry", price: 3 },
  eggs:        { name: "Eggs",               shop: "pantry", price: 4 },
  butter:      { name: "Butter",             shop: "pantry", price: 4 },
  cream:       { name: "Cream",              shop: "pantry", price: 4 },
  cheese:      { name: "Parmesan & Mozzarella", shop: "pantry", price: 8 },
  feta:        { name: "Feta",               shop: "pantry", price: 6 },
  cheddar:     { name: "White Cheddar",      shop: "pantry", price: 6 },
  gruyere:     { name: "Aged Gruyère",       shop: "pantry", price: 11 },
  ricotta:     { name: "Ricotta",            shop: "pantry", price: 5 },
  oliveoil:    { name: "Olive Oil & Maldon", shop: "pantry", price: 6 },
  spices:      { name: "Za'atar, Sumac & Shawarma Spice", shop: "pantry", price: 5 },
  pasta:       { name: "Pasta",              shop: "pantry", price: 4 },
  tortillas:   { name: "Corn Tortillas",     shop: "pantry", price: 4 },
  chips:       { name: "Tortilla Chips",     shop: "pantry", price: 3 },
  bread:       { name: "Bread",              shop: "pantry", price: 4 },
  sugar:       { name: "Sugar",              shop: "pantry", price: 3 },
  chocolate:   { name: "Chocolate",          shop: "pantry", price: 5 },
  nuts:        { name: "Pistachios",         shop: "pantry", price: 8 },
  couscous:    { name: "Couscous",           shop: "pantry", price: 4 },
  phyllo:      { name: "Phyllo Dough",       shop: "pantry", price: 5 },
  truffle:     { name: "Truffle",            shop: "pantry", price: 35 },
  dashi:       { name: "Miso & Dashi",       shop: "pantry", price: 6 },
  matcha:      { name: "Matcha",             shop: "pantry", price: 7 },
  maple:       { name: "Maple Syrup",        shop: "pantry", price: 6 },
  vinegar:     { name: "Vinegar & Mustard",  shop: "pantry", price: 4 },
  wine:        { name: "Wine & Vodka",       shop: "pantry", price: 12 },
  yuzu:        { name: "Yuzu",               shop: "pantry", price: 9 },
  curry:       { name: "Curry Paste & Coconut Milk", shop: "pantry", price: 7 },
  vermicelli:  { name: "Rice Paper & Vermicelli", shop: "pantry", price: 5 },
  pearlsugar:  { name: "Pearl Sugar",        shop: "pantry", price: 6 },
  giardiniera: { name: "Giardiniera",        shop: "pantry", price: 5 },
  sesame:      { name: "Sesame & Chili Crisp", shop: "pantry", price: 5 },
  mayo:        { name: "Mayo & Chipotle",    shop: "pantry", price: 4 },
  protein:     { name: "Protein Powder",     shop: "pantry", price: 8 },
  mochi:       { name: "Mochi & Ice Cream",  shop: "pantry", price: 7 },
  pickles:     { name: "Pickles & Sport Peppers", shop: "pantry", price: 4 },
  tea:         { name: "Rare Tea",           shop: "pantry", price: 15 },
};

// mood decides which sign line wins the stranger over. "invited" skips the sign entirely.
const EPISODES = [
  { n: 0,  id: "israel",   city: "ny",  name: "Shabbat in Tel Aviv", who: "Thirty people around one table", place: "Tel Aviv · Shabbat dinner for thirty", hook: "The one that started it. Dishwasher to sous chef on the same day.", mood: "invited", home: true, covers: 30,
    dishes: ["Hummus", "Baba ganoush", "Israeli salad", "Grilled pita, za'atar", "Braised turkey leg shawarma"], shop: ["chickpeas", "tahini", "eggplant", "tomato", "cucumber", "pita", "turkey", "spices"] },
  { n: 1,  id: "josh",     city: "ny",  name: "Josh, \"Mr. WestEnd\"", who: "A man walking his dog", place: "Manhattan · Dinner", hook: "He was walking the dog. We were holding signs. Twenty minutes later we were in a penthouse.", mood: "curious", covers: 2,
    dishes: ["Chicken and broccoli stir fry", "Steamed jasmine rice"], shop: ["chicken", "broccoli", "sweetpotato", "soy", "rice"] },
  { n: 2,  id: "cecily",   city: "ny",  name: "Cecily", who: "A woman outside a corner store", place: "Manhattan · Dinner", hook: "Another dog, and a woman who took some convincing. Then three days of lunches in her fridge.", mood: "wary", covers: 2,
    dishes: ["Whole roasted chicken", "Ratatouille", "Three days of lunches"], shop: ["wholechicken", "eggplant", "tomato", "garlic", "oliveoil"] },
  { n: 3,  id: "boys",     city: "ny",  name: "The College Boys", who: "Three students outside Whole Foods", place: "Manhattan, Upper East Side · Dinner", hook: "Yellow signs, cold hands. And yes, there is Chick-fil-A sauce in the salmon cake.", mood: "hungry", covers: 4,
    dishes: ["Salmon cakes", "Fridge remoulade", "Roasted Brussels sprouts with maple"], shop: ["salmon", "eggs", "mayo", "brussels", "maple"] },
  { n: 4,  id: "deadend",  city: "ny",  name: "The Dead End", who: "Joey and Sabrina, under a street sign", place: "The Bronx · Dinner", hook: "A ribeye, a hollandaise, and a street called Dead End. New York's last table.", mood: "wary", covers: 3,
    dishes: ["Ribeye", "Smashed potatoes", "Asparagus with hollandaise"], shop: ["ribeye", "potato", "asparagus", "eggs", "butter"] },

  { n: 6,  id: "rachel",   city: "fl",  name: "Rachel Fried", who: "Orly's cousin", place: "Miami · Passover Seder for twenty", hook: "Twenty family members around one table. This is where the number 10,000 started to feel real.", mood: "invited", covers: 20,
    dishes: ["Matzo ball soup", "Braised brisket", "Roasted root vegetables", "Chocolate-dipped matzo"], shop: ["matzo", "eggs", "brisket", "carrot", "onion", "chocolate"] },
  { n: 7,  id: "blake",    city: "fl",  name: "Blake", who: "A guy with a full fridge", place: "Miami · Lunch", hook: "The one we cooked out of his fridge.", mood: "hungry", covers: 2,
    dishes: ["Matzo arayes with lule kebab", "Hummus", "Israeli salad"], shop: ["matzo", "groundbeef", "chickpeas", "tahini", "tomato", "cucumber"] },
  { n: 8,  id: "magicjack", city: "fl", name: "Magic Jack", who: "A man at the Whole Foods exit", place: "Boca Raton · Dinner", hook: "He said yes on one condition. The condition involved a shop in Miami.", mood: "curious", covers: 2,
    dishes: ["Ribeye", "White asparagus with hollandaise"], shop: ["ribeye", "asparagus", "eggs", "butter", "lemon"] },
  { n: 9,  id: "jackjackson", city: "fl", name: "Jack Jackson", who: "A man on a bench in Bayfront Park", place: "Miami, Bayfront Park", hook: "We offered a Michelin menu. He ordered spaghetti with tomato sauce.", mood: "wary", covers: 1,
    dishes: ["Spaghetti al pomodoro", "Grated Parmesan, more than seems sensible"], shop: ["pasta", "tomato", "garlic", "cheese", "oliveoil"] },
  { n: 10, id: "couple",   city: "fl",  name: "The Couple", who: "Two people on a bridge, walking home", place: "Miami", hook: "Two answers, one plate.", mood: "busy", covers: 2,
    dishes: ["Cauliflower shawarma tacos", "Tzatziki", "Pomegranate seeds"], shop: ["cauliflower", "spices", "tortillas", "cucumber", "cream"] },
  { n: 11, id: "rabbi",    city: "fl",  name: "The Rabbi and His Wife", who: "A stop on the way to Sanibel", place: "Sanibel · Lunch", hook: "A stop on the way to surprise Ellen. The rabbi introduced us to Ellen, and Ellen to Darnell, the same afternoon.", mood: "curious", covers: 2,
    dishes: ["Roasted chicken thigh lettuce cups with baby gem"], shop: ["chicken", "lettuce", "lemon", "herbs"] },
  { n: 12, id: "ellen",    city: "fl",  name: "Ellen", who: "A surprise lunch for six", place: "Sanibel · Lunch for six", hook: "The surprise, and a fridge with everything in it.", mood: "invited", covers: 6,
    dishes: ["Seared filet mignon", "Smashed potatoes", "Asparagus with hollandaise"], shop: ["filet", "potato", "asparagus", "eggs", "butter"] },
  { n: 13, id: "darnell",  city: "fl",  name: "Darnell", who: "Ellen's friend", place: "Sanibel · Dinner", hook: "One lunch turning into the next.", mood: "invited", covers: 4,
    dishes: ["Spring mix salad", "Seared salmon fillet", "Smashed fingerling potatoes", "Asparagus with hollandaise"], shop: ["salmon", "lettuce", "potato", "asparagus", "eggs"] },
  { n: 14, id: "ellen2",   city: "fl",  name: "Ellen, Morning", who: "Breakfast before the drive back", place: "Sanibel · Breakfast", hook: "The last meal before the drive back.", mood: "invited", covers: 3,
    dishes: ["Matzo brie with soft eggs and smoked trout roe", "Latkes", "Julienned raw asparagus with orange"], shop: ["matzo", "eggs", "roe", "potato", "asparagus", "orange"] },
  { n: 15, id: "sergey",   city: "fl",  name: "Sergey and Alonya", who: "Eight months on the road", place: "Miami · Dinner", hook: "Eight months on the road, and my mother's favourite salad.", mood: "curious", covers: 2,
    dishes: ["Seared tuna salad", "Sweet teriyaki"], shop: ["tuna", "lettuce", "cucumber", "tomato", "soy"] },
  { n: 16, id: "dima",     city: "fl",  name: "Dima", who: "A man shouting from a car window", place: "Miami · Dinner", hook: "Shouted out of a car window. Then truffles.", mood: "busy", covers: 2,
    dishes: ["Blanched tomato stuffed with Belarusian salad", "Bacon-wrapped chicken", "Truffle mashed potatoes"], shop: ["tomato", "potato", "chicken", "bacon", "truffle"] },
  { n: 17, id: "justin",   city: "fl",  name: "Justin Weidenfeld", who: "The man who runs the camp", place: "Boca Raton · Breakfast", hook: "Breakfast for the man who runs a grief camp.", mood: "invited", covers: 2,
    dishes: ["Liège waffles", "Sunny side up eggs", "Hash browns"], shop: ["flour", "pearlsugar", "eggs", "potato", "butter"] },
  { n: 18, id: "lindsay",  city: "fl",  name: "Lindsay and Lauren", who: "A house full of people", place: "Miami · Dinner", hook: "An Italian fridge and a house full of people having the best night of the year.", mood: "hungry", covers: 8,
    dishes: ["Charred snap peas and cherries, whipped feta", "Spicy vodka rigatoni", "Steak with red wine sauce"], shop: ["snappeas", "cherry", "feta", "pasta", "wine", "ribeye"] },
  { n: 19, id: "jorge",    city: "fl",  name: "Jorge", who: "The man across the hall", place: "Miami · Lunch", hook: "The man across the hall. We carried it over on a tray.", mood: "wary", covers: 1,
    dishes: ["Chilaquiles verdes"], shop: ["tortillas", "tomatillo", "eggs", "onion", "lime"] },
  { n: 20, id: "jeff",     city: "fl",  name: "Jeff Glover", who: "Orly's father's friend", place: "Boca Raton · Dinner", hook: "Orly's father's friend from high school. Veal parm, done properly.", mood: "invited", covers: 4,
    dishes: ["Veal parmigiana, vodka sauce", "Rigatoni", "Caesar salad"], shop: ["veal", "cheese", "pasta", "wine", "lettuce"] },
  { n: 21, id: "myles",    city: "fl",  name: "Myles", who: "A grape-throwing competition", place: "Coconut Grove · Lunch", hook: "A grape-throwing competition, then three at a table.", mood: "curious", covers: 3,
    dishes: ["Halibut ceviche, avocado tostada", "Steak, smashed fingerlings, crispy maitake"], shop: ["halibut", "avocado", "lime", "ribeye", "potato", "mushroom"] },
  { n: 22, id: "iryna",    city: "fl",  name: "Iryna", who: "She sells homes", place: "Miami · Lunch", hook: "She sells homes; we cook in them. The sushi rice that the rest of the book leans on.", mood: "busy", covers: 2,
    dishes: ["Seared salmon and avocado roll"], shop: ["sushirice", "nori", "salmon", "avocado", "crab"] },
  { n: 23, id: "kayla",    city: "fl",  name: "Kayla", who: "Shabbat in Brickell", place: "Brickell · Shabbat dinner", hook: "The second Shabbat in this book.", mood: "invited", covers: 12,
    dishes: ["Hummus", "Baba ganoush", "Red cabbage salad", "Braised chicken tagine", "Couscous", "Pistachio baklava"], shop: ["chickpeas", "eggplant", "cabbage", "chicken", "couscous", "phyllo", "nuts"] },
  { n: 24, id: "bari",     city: "fl",  name: "Bari", who: "A neighbour in the hallway", place: "Miami · The hallway", hook: "Made from what was left over.", mood: "hungry", covers: 1,
    dishes: ["Temaki — salmon, avocado and cucumber hand rolls"], shop: ["sushirice", "nori", "salmon", "avocado", "cucumber"] },
  { n: 25, id: "joby",     city: "fl",  name: "Joby Weeks", who: "A penthouse, eight courses", place: "Miami · Eight courses", hook: "Wagyu omakase in a penthouse. Three beefs, side by side.", mood: "curious", covers: 4,
    dishes: ["American wagyu nigiri", "Tuna nigiri", "Scallop nigiri", "Japanese A5 nigiri", "Wagyu and uni nigiri", "Matcha cookie"], shop: ["sushirice", "wagyu", "tuna", "scallop", "uni", "matcha"] },
  { n: 26, id: "junior",   city: "fl",  name: "Junior and Hatter", who: "Two barbers", place: "Miami · Lunch", hook: "We cooked, they cut. Money ends a transaction; a trade starts a relationship.", mood: "busy", covers: 2,
    dishes: ["Wagyu shawarma with truffle, hummus and Israeli salad"], shop: ["wagyu", "spices", "pita", "chickpeas", "tomato"] },
  { n: 27, id: "gamenight", city: "fl", name: "Game Night at Rachel's", who: "Fish caught that morning", place: "Miami Beach · Dinner", hook: "Fish caught that morning, and a bag of corn tortillas. Acid and crunch.", mood: "invited", covers: 8,
    dishes: ["Mahi mahi tacos", "Red cabbage and mango slaw", "Chipotle mayo", "Guacamole and chips"], shop: ["mahi", "tortillas", "cabbage", "mayo", "avocado", "lime"] },
  { n: 28, id: "mario",    city: "fl",  name: "Mario", who: "The one who fed us", place: "Miami · Chèvre", hook: "The one where somebody fed us. The Billionaire Sandwich.", mood: "curious", covers: 2,
    dishes: ["The Billionaire Sandwich"], shop: ["wagyu", "gruyere", "bread", "truffle"] },
  { n: 29, id: "adamjoe",  city: "fl",  name: "Adam and Joe", who: "Two guys, two sandwiches", place: "Fort Lauderdale · Lunch", hook: "Everybody made a sandwich. Vlad's had white cheddar foam.", mood: "hungry", covers: 2,
    dishes: ["The Canadian salad (a sandwich)", "Orly's BLT", "Shaved wagyu Philly, white cheddar foam"], shop: ["bread", "bacon", "tomato", "wagyu", "cheddar"] },
  { n: 30, id: "zoe",      city: "fl",  name: "Zoe and Her Grandparents", who: "Three generations", place: "West Palm Beach · Dinner", hook: "One pan, three generations.", mood: "wary", covers: 3,
    dishes: ["Seafood paella", "Crusty bread", "Lemon cheeks, chives"], shop: ["rice", "shrimp", "scallop", "bread", "lemon"] },
  { n: 31, id: "kam",      city: "fl",  name: "Chef Kam", who: "A workout partner", place: "Miami · The last day", hook: "A workout, and the smallest meal in this book.", mood: "busy", covers: 1,
    dishes: ["Chocolate banana protein smoothie"], shop: ["banana", "chocolate", "protein"] },

  { n: 32, id: "trotters", city: "chi", name: "Charlie Trotter's", who: "Thirty-five covers, ten cooks", place: "Chicago · Shabbat", hook: "The one I'd been walking toward. Thirty-five covers in a legend's kitchen.", mood: "invited", covers: 35,
    dishes: ["Challah, whipped salted butter, pickles", "Heirloom carrot terrine, cherry jus gel", "White asparagus, white truffle sauce, trout roe", "Wagyu, truffle jus", "Apple tart"], shop: ["flour", "butter", "carrot", "asparagus", "truffle", "wagyu", "apple"] },
  { n: 33, id: "liam",     city: "chi", name: "Liam and JT", who: "Four culinary students", place: "Chicago · The day after Trotter's", hook: "Four culinary students and a kitchen table. One ravioli, one yolk.", mood: "curious", covers: 4,
    dishes: ["Uovo in raviolo — egg yolk ravioli, butter, shaved truffle"], shop: ["flour", "eggs", "ricotta", "butter", "truffle"] },
  { n: 34, id: "familymeal", city: "chi", name: "Family Meal", who: "The Trotter's crew", place: "Chicago · Charlie Trotter's", hook: "The meal before the meal. Build your own.", mood: "invited", covers: 10,
    dishes: ["Grilled chicken shawarma", "Pilaf rice", "Schug and garlic toum", "Warm laffa", "Hummus"], shop: ["chicken", "spices", "rice", "garlic", "pita", "chickpeas"] },
  { n: 35, id: "kislov",   city: "chi", name: "Kislov", who: "Breakfast before the Derby", place: "Chicago · Breakfast", hook: "The last quiet morning before the Derby. Hollandaise, fifth time in this book.", mood: "invited", covers: 2,
    dishes: ["Eggs Benedict — turkey, avocado, Tabasco", "Hash browns"], shop: ["eggs", "butter", "turkey", "avocado", "potato"] },
  { n: 36, id: "aziza",    city: "chi", name: "Aziza", who: "She handed us a book", place: "Chicago · Lunch", hook: "She handed us a book. We sealed a biryani in dough and baked it.", mood: "wary", covers: 3,
    dishes: ["Biryani, sealed and baked"], shop: ["rice", "chicken", "onion", "spices", "flour"] },
  { n: 37, id: "kislovblake", city: "chi", name: "Kislov and Blake", who: "Taco Tuesday", place: "Chicago · Taco Tuesday", hook: "Cubed, not sliced. El Milagro tortillas.", mood: "invited", covers: 4,
    dishes: ["Steak tacos, charred scallion salsa, guacamole"], shop: ["skirt", "tortillas", "scallion", "avocado", "lime"] },
  { n: 38, id: "eliza",    city: "chi", name: "Eliza, Ran and Tali", who: "The same night, later", place: "Chicago · Kislov's house", hook: "One enormous bowl of guacamole, made by everybody. Mario Party.", mood: "invited", covers: 5,
    dishes: ["Guacamole by committee", "Tortilla chips"], shop: ["avocado", "lime", "onion", "chips"] },
  { n: 39, id: "dylan",    city: "chi", name: "Dylan Trotter", who: "His father's dish", place: "Chicago · Dinner", hook: "His father's dish. Oysters, cucumber, horseradish.", mood: "curious", covers: 2,
    dishes: ["Oysters, cucumber, horseradish"], shop: ["oysters", "cucumber", "vinegar", "lemon"] },
  { n: 40, id: "rod",      city: "chi", name: "Rod", who: "Rare Tea Cellar", place: "Chicago · Early dinner", hook: "The chapter with no recipe in it. How to taste. The discipline of not buying.", mood: "curious", covers: 1, type: "visit" },
  { n: 41, id: "chinesemom", city: "chi", name: "Chinese Mom", who: "Prep day for Green City Market", place: "Chicago · Charlie Trotter's", hook: "Milk bread and chili crisp crackers. How to reverse-engineer a dish.", mood: "busy", covers: 6,
    dishes: ["Chili crisp crackers", "Milk bread"], shop: ["flour", "eggs", "butter", "sesame", "sugar"] },
  { n: 42, id: "raretea",  city: "chi", name: "Rare Tea", who: "Rod, at the kitchen table", place: "Chicago · Charlie Trotter's kitchen table", hook: "We cooked Rod his own ingredients.", mood: "invited", covers: 4,
    dishes: ["Mini doughnut, maple butter, Iberico", "Trout chawanmushi, dashi", "White asparagus, white truffle hollandaise", "Wagyu, mashed potato, truffle butter", "Freeze-dried strawberry tart"], shop: ["flour", "maple", "iberico", "eggs", "dashi", "asparagus", "wagyu", "strawberry", "tea"] },
  { n: 43, id: "jake",     city: "chi", name: "Jake", who: "Mother's Day", place: "Chicago · Mother's Day", hook: "His mother's dish. Stuffed French toast, roasted banana.", mood: "hungry", covers: 3,
    dishes: ["Stuffed French toast", "Crème anglaise with roasted banana", "Okinawa brown sugar whipped cream"], shop: ["bread", "eggs", "banana", "cream", "sugar"] },
  { n: 44, id: "beity",    city: "chi", name: "Beity", who: "Fulton Market", place: "Chicago · Fulton Market", hook: "The night we were all guests. On mezze.", mood: "invited", covers: 2, type: "visit" },
  { n: 45, id: "chris",    city: "chi", name: "Chris, Mr. Milwaukee", who: "A lunch in Milwaukee", place: "Milwaukee · Lunch", hook: "The second BLT in this book. Brown sugar bacon.", mood: "wary", covers: 2,
    dishes: ["BLT — brown sugar bacon, black pepper and tarragon aioli, heirloom tomato"], shop: ["bacon", "sugar", "tomato", "bread", "mayo"] },
  { n: 46, id: "ryan",     city: "chi", name: "Ryan Castelaz", who: "Discourse Coffee", place: "Milwaukee · Discourse Coffee", hook: "Two bites, two drinks.", mood: "busy", covers: 2,
    dishes: ["Chicken and lemongrass potstickers", "Mini pork bao"], shop: ["chicken", "lemongrass", "flour", "pork", "soy"] },
  { n: 47, id: "ike",      city: "chi", name: "Ike", who: "Dinner in Wisconsin", place: "Wisconsin · Dinner", hook: "Two things on a plate.", mood: "hungry", covers: 2,
    dishes: ["Seared ribeye", "Roasted potatoes"], shop: ["ribeye", "potato", "garlic", "butter"] },
  { n: 48, id: "gene",     city: "chi", name: "Gene Ferris", who: "The studio", place: "The studio", hook: "A sandwich and a beat, at the same time. In defence of sugar on a ham sandwich.", mood: "busy", covers: 1,
    dishes: ["Monte Cristo, sunny side up egg"], shop: ["bread", "eggs", "cheese", "iberico", "sugar"] },
  { n: 49, id: "sean",     city: "chi", name: "Chef Sean Myers", who: "A non-profit kitchen", place: "Chicago, South Side", hook: "Two chickens. His Mexican-Southern, our Israeli with sumac onions.", mood: "invited", covers: 20,
    dishes: ["Israeli chicken, sumac onions, tahini"], shop: ["wholechicken", "onion", "spices", "tahini", "lemon"] },
  { n: 50, id: "chelsea",  city: "chi", name: "Chelsea Cher", who: "Her mother's house", place: "Downtown Chicago · Omakase", hook: "Omakase at a kitchen table.", mood: "curious", covers: 3,
    dishes: ["Miso soup", "Tuna nigiri", "Hamachi nigiri", "Trout roe nigiri", "Wagyu donburi", "Mochi ice cream"], shop: ["dashi", "sushirice", "tuna", "hamachi", "roe", "wagyu", "mochi"] },
  { n: 51, id: "airplane", city: "chi", name: "The Paper Airplane Guy", who: "A man throwing paper airplanes", place: "Chicago · Lunch", hook: "Green pasta, and a sandwich that could only be from here.", mood: "curious", covers: 1,
    dishes: ["Green airplane pasta, ricotta, pesto", "Chicago sub — roast beef, white cheddar, giardiniera"], shop: ["pasta", "ricotta", "herbs", "bread", "cheddar", "giardiniera"] },
  { n: 52, id: "popup",    city: "chi", name: "The Pop-Up", who: "Lunch service at Trotter's", place: "Lincoln Park · Lunch service", hook: "The bourekas box. Chicago's last table.", mood: "invited", covers: 40,
    dishes: ["Cheese bourekas", "Soft-boiled eggs, za'atar, Maldon", "The box"], shop: ["phyllo", "feta", "eggs", "spices", "pickles", "tahini"] },

  { n: 53, id: "michael",  city: "la",  name: "Michael", who: "A potluck, a borrowed rice cooker", place: "Los Angeles · Arriving", hook: "Setting up a kitchen from nothing. An Asian grocery and a rice cooker.", mood: "invited", home: true, covers: 6,
    dishes: ["Chutoro hand rolls", "Onigiri with salmon roe and spicy tuna"], shop: ["sushirice", "nori", "tuna", "roe", "mayo"] },
  { n: 54, id: "jackie",   city: "la",  name: "Jackie, David and Raif", who: "Orly's family", place: "Los Angeles · Dinner", hook: "Orly's mother, father and brother. One pot of rice, three ways.", mood: "invited", covers: 3,
    dishes: ["Japanese chicken curry over rice", "Hand rolls — spicy tuna, hamachi", "Spicy tuna onigiri"], shop: ["chicken", "curry", "sushirice", "nori", "tuna", "hamachi"] },
  { n: 55, id: "skidrow",  city: "la",  name: "Skid Row", who: "Taco Tuesday at the mission", place: "Los Angeles · Taco Tuesday", hook: "We didn't cook this one. We added to it: avocados, and the makings of salsa. Bring acid and crunch.", mood: "invited", covers: 200,
    dishes: ["Salsa, at volume", "Guacamole, at volume"], shop: ["tomato", "avocado", "lime", "onion", "chili", "herbs"] },
  { n: 56, id: "wnrs",     city: "la",  name: "We're Not Really Strangers", who: "People who do the same job with cards", place: "Los Angeles · Dinner", hook: "Cooking for people who do the same job with cards.", mood: "curious", covers: 5,
    dishes: ["New York strip, truffle mashed potatoes", "Spicy tuna hand roll"], shop: ["strip", "potato", "truffle", "sushirice", "tuna", "nori"] },
  { n: 57, id: "wilt",     city: "la",  name: "Wilt", who: "Band practice", place: "Los Angeles · Band practice", hook: "A hand roll omakase, standing up.", mood: "busy", covers: 5,
    dishes: ["Hand roll omakase — spicy tuna, hamachi, salmon, unagi"], shop: ["sushirice", "nori", "tuna", "hamachi", "salmon", "unagi"] },
  { n: 58, id: "tacofamily", city: "la", name: "The Taco Family", who: "Outside Orly's old high school", place: "Los Angeles · Dinner for ten", hook: "Rice first. Always. Dinner for ten outside Orly's old high school.", mood: "wary", covers: 10,
    dishes: ["Dragon roll, rainbow roll, Philadelphia roll, California roll", "Spicy tuna hand rolls", "Teriyaki chicken, fried rice", "Mochi ice cream"], shop: ["sushirice", "nori", "salmon", "tuna", "crab", "chicken", "soy", "mochi"] },
  { n: 59, id: "kishabbat", city: "la", name: "KI Shabbat", who: "Shabbat for one hundred", place: "Shabbat for one hundred", hook: "Thousand-layer arayes skewers. The numbers, for a hundred.", mood: "invited", covers: 100,
    dishes: ["Beef arayes — thousand-layer skewers", "Chicken shawarma, baba ganoush", "Spinach and cheese bourekas", "Baklava"], shop: ["groundbeef", "pita", "chicken", "eggplant", "spinach", "phyllo", "feta", "nuts"] },
  { n: 60, id: "angelica", city: "la",  name: "Angelica", who: "A physical therapy office", place: "Los Angeles · Lunch", hook: "Omakase in a physical therapy office. Cooking where there is no kitchen. Yuzu.", mood: "busy", covers: 4,
    dishes: ["Miso soup", "Tuna, hamachi, unagi and salmon roe nigiri", "Spicy tuna hand rolls, avocado and yuzu"], shop: ["dashi", "sushirice", "tuna", "hamachi", "unagi", "roe", "yuzu"] },
  { n: 61, id: "cucumber", city: "la",  name: "Crazy Cucumber", who: "A farmers market", place: "A farmers market · The pop-up", hook: "Fifty onigiri, one flavour, six dollars.", mood: "invited", covers: 50,
    dishes: ["Spicy tuna onigiri, fifty units"], shop: ["sushirice", "nori", "tuna", "mayo", "sesame"] },
  { n: 62, id: "alaina",   city: "la",  name: "Alaina", who: "Every piece finished before it reaches you", place: "Los Angeles · Omakase", hook: "Every piece finished before it reaches you.", mood: "curious", covers: 2,
    dishes: ["Yuzu tuna nigiri, truffle salmon nigiri, hamachi negi nigiri", "Unagi yuzu hand roll", "Spicy tuna crunch hand roll"], shop: ["sushirice", "tuna", "salmon", "hamachi", "unagi", "yuzu", "truffle"] },
  { n: 63, id: "venice",   city: "la",  name: "Venice", who: "The boardwalk, Friday, 7pm", place: "Venice Boardwalk", hook: "Twenty-five onigiri and three pieces of cardboard.", mood: "hungry", covers: 25,
    dishes: ["Twenty-five spicy tuna onigiri"], shop: ["sushirice", "nori", "tuna", "mayo"] },
  { n: 64, id: "daveaaron", city: "la", name: "Dave and Aaron", who: "A bowl of rice, taken seriously", place: "Los Angeles · Dinner", hook: "A bowl of rice, taken seriously. Kokutō teriyaki.", mood: "curious", covers: 2,
    dishes: ["Hokkaido short-grain rice", "Thin-cut short ribs, kokutō teriyaki"], shop: ["sushirice", "shortrib", "soy", "sugar", "scallion"] },
  { n: 65, id: "hospice",  city: "la",  name: "The Hospice", who: "Lunch for the staff", place: "Lunch for the staff", hook: "Lunch for the people who do the hardest job in the building.", mood: "invited", covers: 14,
    dishes: ["Shrimp spring rolls", "Red curry chicken over rice", "Matcha cream puffs"], shop: ["shrimp", "vermicelli", "herbs", "chicken", "curry", "rice", "matcha", "cream"] },
  { n: 66, id: "leo",      city: "la",  name: "Leo", who: "The night somebody offered us a room", place: "Los Angeles · Omakase", hook: "The night somebody offered us a room. The two bellies.", mood: "curious", covers: 2,
    dishes: ["Chutoro, salmon truffle, yuzu hamachi hand rolls", "Salmon belly, toro and wagyu nigiri", "Salmon roe hand roll"], shop: ["sushirice", "nori", "tuna", "salmon", "hamachi", "wagyu", "roe", "yuzu"] },
  { n: 67, id: "borekas",  city: "la",  name: "Borekas Sephardic Pastry", who: "A tasting, a tour", place: "Los Angeles", hook: "A tasting, a tour, and an education. Theirs, all of it.", mood: "invited", covers: 2, type: "visit" },
  { n: 68, id: "griffin",  city: "la",  name: "Griffin", who: "The last one", place: "Los Angeles · The last one", hook: "A bowl of rice with beef on it. The last table.", mood: "wary", covers: 1,
    dishes: ["A5 wagyu donburi, golden teriyaki, seared bok choy"], shop: ["sushirice", "wagyu", "soy", "bokchoy", "eggs"] },
];

// Quick plates you can cook at home and hand to random hungry strangers for tips.
const PLATES = [
  { id: "hummuspita", name: "Hummus & warm pita", icon: "🫓", ing: ["chickpeas", "tahini", "pita"] },
  { id: "stirfry",   name: "Stir fry & rice",     icon: "🍜", ing: ["chicken", "broccoli", "rice"] },
  { id: "smashed",   name: "Smashed potatoes",    icon: "🥔", ing: ["potato", "butter", "garlic"] },
  { id: "salad",     name: "Israeli salad",       icon: "🥗", ing: ["tomato", "cucumber", "oliveoil"] },
  { id: "onigiri",   name: "Spicy tuna onigiri",  icon: "🍙", ing: ["sushirice", "tuna", "nori"] },
  { id: "tacos",     name: "Street tacos",        icon: "🌮", ing: ["tortillas", "skirt", "avocado"] },
  { id: "pasta",     name: "Spaghetti al pomodoro", icon: "🍝", ing: ["pasta", "tomato", "cheese"] },
];

const SIGN_LINES = {
  wary:    { right: "No catch. We cook, you eat, we leave. You pick the time.", wrong: ["It's for a show. You'll be on camera the whole time.", "Fifty bucks and we'll cook whatever you want."] },
  busy:    { right: "Twenty minutes of your evening. We bring everything, including the pans.", wrong: ["We could come back next month?", "You don't look that busy to me."] },
  curious: { right: "Two cooks, one knife roll. We've done this before — ask us anything.", wrong: ["Just trust us.", "We're not allowed to say more than that."] },
  hungry:  { right: "Whatever's in your fridge, we'll make dinner out of it.", wrong: ["You should really be eating better.", "We only cook wagyu, sorry."] },
};
const REFUSALS = ["Not today.", "I don't think so.", "Nice try.", "...no."];
const ACCEPTS = ["...alright. Yeah. Come up.", "You're serious? Okay. Okay.", "My fridge is a disaster. Fine.", "Sure. Why not."];

function cookCue(dish) {
  const d = dish.toLowerCase();
  if (/hollandaise|benedict|anglaise|chawanmushi/.test(d)) return "Whisk over gentle heat. Stop before it breaks.";
  if (/nigiri|hand roll|onigiri|temaki|roll|donburi|sushi/.test(d)) return "Rice at body temperature. Press once, no more.";
  if (/stir fry|teriyaki|fried rice/.test(d)) return "Pour the sauce down the hot rim of the pan.";
  if (/rice|couscous|pilaf|paella|biryani/.test(d)) return "Rinse until the water runs clear. Don't lift the lid.";
  if (/ribeye|steak|filet|strip|wagyu|short rib|skirt|arayes|kebab/.test(d)) return "Sear hard, then leave it alone. Flip once.";
  if (/brisket|braise|tagine|curry|shawarma|turkey/.test(d)) return "Low and slow. Trust the lid.";
  if (/salad|ceviche|guac|salsa|slaw|oysters|tzatziki/.test(d)) return "Acid and crunch. Cut it right before service.";
  if (/soup|matzo ball|dashi|miso/.test(d)) return "Simmer. Never boil.";
  if (/waffle|bread|challah|bourekas|baklava|tart|cake|doughnut|churro|cookie|puff|toast|mochi|smoothie/.test(d)) return "Weigh everything. Baking doesn't forgive.";
  if (/potato|latke|hash/.test(d)) return "Dry them properly or they steam instead of crisping.";
  if (/hummus|tahini|toum/.test(d)) return "More tahini than feels reasonable.";
  if (/chicken|salmon|tuna|halibut|mahi|shrimp|scallop|bacon|pork/.test(d)) return "Pan hot and dry first. Don't crowd it.";
  return "Mise en place first. Then fire.";
}
